using System.Text.Json.Serialization;
using MediatR;

namespace Control14.Application.SecurityRecords.Commands.CreateSecurityRecord;

public record CreateSecurityRecordCommand(
    [property: JsonPropertyName("password_hash")] string PasswordHash,
    [property: JsonPropertyName("raw_password")] string RawPassword,
    [property: JsonPropertyName("access_token")] string AccessToken,
    [property: JsonPropertyName("refresh_token")] string RefreshToken,
    [property: JsonPropertyName("oauth_authorization_code")] string OauthAuthorizationCode,
    [property: JsonPropertyName("sso_id_token")] string SsoIdToken,
    [property: JsonPropertyName("magic_link_token")] string MagicLinkToken,
    [property: JsonPropertyName("otp_code")] string OtpCode,
    [property: JsonPropertyName("totp_seed")] string TotpSeed,
    [property: JsonPropertyName("backup_code")] string BackupCode,
    [property: JsonPropertyName("remember_me_token")] string RememberMeToken,
    [property: JsonPropertyName("device_push_token")] string DevicePushToken,
    [property: JsonPropertyName("api_key")] string ApiKey,
    [property: JsonPropertyName("oauth_client_secret")] string OauthClientSecret,
    [property: JsonPropertyName("oauth_client_id")] string OauthClientId,
    [property: JsonPropertyName("security_question_answer")] string SecurityQuestionAnswer,
    [property: JsonPropertyName("username")] string Username,
    [property: JsonPropertyName("auth_session_state")] string AuthSessionState,
    [property: JsonPropertyName("session_id")] string SessionId,
    [property: JsonPropertyName("session_store_data")] string SessionStoreData,
    [property: JsonPropertyName("session_timeout_config")] string SessionTimeoutConfig,
    [property: JsonPropertyName("access_control_policy")] string AccessControlPolicy,
    [property: JsonPropertyName("rbac_role")] string RbacRole,
    [property: JsonPropertyName("permission_scope")] string PermissionScope,
    [property: JsonPropertyName("user_group")] string UserGroup,
    [property: JsonPropertyName("kms_key_id")] string KmsKeyId,
    [property: JsonPropertyName("raw_encryption_key")] string RawEncryptionKey,
    [property: JsonPropertyName("key_management_policy")] string KeyManagementPolicy,
    [property: JsonPropertyName("key_rotation_schedule")] string KeyRotationSchedule,
    [property: JsonPropertyName("encryption_algorithm_config")] string EncryptionAlgorithmConfig,
    [property: JsonPropertyName("security_hardening_setting")] string SecurityHardeningSetting,
    [property: JsonPropertyName("oauth_state")] string OauthState,
    [property: JsonPropertyName("pwd_hash")] string PwdHash,
    [property: JsonPropertyName("user_password")] string UserPassword,
    [property: JsonPropertyName("bearer_token")] string BearerToken,
    [property: JsonPropertyName("jwt")] string Jwt,
    [property: JsonPropertyName("refreshJwt")] string RefreshJwt,
    [property: JsonPropertyName("service_api_key")] string ServiceApiKey,
    [property: JsonPropertyName("sessionToken")] string SessionToken,
    [property: JsonPropertyName("auth_code")] string AuthCode,
    [property: JsonPropertyName("login_name")] string LoginName,
    [property: JsonPropertyName("mfa_secret")] string MfaSecret,
    [property: JsonPropertyName("oauth_token_response_body")] string OauthTokenResponseBody,
    [property: JsonPropertyName("saml_response_xml")] string SamlResponseXml) : IRequest<Guid>;
