using System.Text.Json.Serialization;
using Control14.Application.DTOs;
using MediatR;

namespace Control14.Application.FinancialPaymentRecords.Commands.UpdateFinancialPaymentRecord;

public record UpdateFinancialPaymentRecordCommand(
    Guid Id,
    [property: JsonPropertyName("bank_account_number")] string BankAccountNumber,
    [property: JsonPropertyName("sort_code")] string SortCode,
    [property: JsonPropertyName("iban")] string Iban,
    [property: JsonPropertyName("swift_bic")] string SwiftBic,
    [property: JsonPropertyName("card_pan")] string CardPan,
    [property: JsonPropertyName("card_expiry")] string CardExpiry,
    [property: JsonPropertyName("card_cvv")] string CardCvv,
    [property: JsonPropertyName("cardholder_name")] string CardholderName,
    [property: JsonPropertyName("card_token")] string CardToken,
    [property: JsonPropertyName("transaction_id")] string TransactionId,
    [property: JsonPropertyName("transaction_amount")] double TransactionAmount,
    [property: JsonPropertyName("txn_currency")] string TxnCurrency,
    [property: JsonPropertyName("transaction_date")] string TransactionDate,
    [property: JsonPropertyName("fx_rate")] double FxRate,
    [property: JsonPropertyName("tax_amount")] double TaxAmount,
    [property: JsonPropertyName("tip_amount")] double TipAmount,
    [property: JsonPropertyName("fee_amount")] double FeeAmount,
    [property: JsonPropertyName("auth_code")] string AuthCode,
    [property: JsonPropertyName("auth_timestamp")] string AuthTimestamp,
    [property: JsonPropertyName("capture_timestamp")] string CaptureTimestamp,
    [property: JsonPropertyName("subscription_mandate_id")] string SubscriptionMandateId,
    [property: JsonPropertyName("payment_method_id")] string PaymentMethodId,
    [property: JsonPropertyName("stripe_customer_id")] string StripeCustomerId,
    [property: JsonPropertyName("fraud_risk_score")] double FraudRiskScore,
    [property: JsonPropertyName("merchant_id")] string MerchantId,
    [property: JsonPropertyName("mcc")] string Mcc,
    [property: JsonPropertyName("bankruptcy_filing")] string BankruptcyFiling,
    [property: JsonPropertyName("tax_return_document")] string TaxReturnDocument,
    [property: JsonPropertyName("creditCardNumber")] string CreditCardNumber,
    [property: JsonPropertyName("pan")] string Pan,
    [property: JsonPropertyName("cvv2")] string Cvv2,
    [property: JsonPropertyName("expMonth")] string ExpMonth,
    [property: JsonPropertyName("accountNumber")] string AccountNumber,
    [property: JsonPropertyName("international_bank_account")] string InternationalBankAccount,
    [property: JsonPropertyName("amount")] double Amount,
    [property: JsonPropertyName("txnId")] string TxnId,
    [property: JsonPropertyName("nameOnCard")] string NameOnCard,
    [property: JsonPropertyName("iso_currency")] string IsoCurrency,
    [property: JsonPropertyName("mid")] string Mid,
    [property: JsonPropertyName("paymentMethodToken")] string PaymentMethodToken,
    [property: JsonPropertyName("cardholder_legal_name")] string CardholderLegalName,
    [property: JsonPropertyName("user_iban")] string UserIban,
    [property: JsonPropertyName("stripe_external_customer_id")] string StripeExternalCustomerId,
    [property: JsonPropertyName("w2_tax_form")] string W2TaxForm,
    [property: JsonPropertyName("payment_receipt_json")] string PaymentReceiptJson,
    [property: JsonPropertyName("authorization_response_blob")] string AuthorizationResponseBlob,
    [property: JsonPropertyName("credit_card_statement")] string CreditCardStatement) : IRequest<FinancialPaymentRecordDto?>;
